project 'AVCam Swift.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'
use_frameworks!
target 'AVCam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Lumina'

  # Pods for AVCam

end
